# Generated by Django 4.2.11 on 2024-06-06 09:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_inventories_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventories',
            name='images',
            field=models.ManyToManyField(related_name='Inventories_images', to='my_app.inventoryimage', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'svg'])]),
        ),
    ]
