# Generated by Django 4.2.11 on 2024-06-06 09:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_inventories_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventories',
            name='images',
            field=models.ManyToManyField(related_name='Inventories_images', to='my_app.inventoryimage'),
        ),
        migrations.AlterField(
            model_name='inventoryimage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='Inventories/images', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'svg'])]),
        ),
    ]
