# Generated by Django 4.2.11 on 2024-06-10 09:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_alter_inventories_images_alter_inventoryimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryimage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='Inventories/images', validators=[django.core.validators.FileExtensionValidator(['.png', '.jpg', '.svg'])]),
        ),
    ]
